APT::FTPArchive::Release::Origin "windenntw";
APT::FTPArchive::Release::Label "windenntw";
APT::FTPArchive::Release::Suite "windenntw";
APT::FTPArchive::Release::Codename "windenntw";
APT::FTPArchive::Release::Architectures "amd64";
APT::FTPArchive::Release::Components "windenntw";
APT::FTPArchive::Release::Description "windenntw Debian Packages";
